# Copyright 2019 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
apiVersion: v1
kind: Service
metadata:
  name: myfirst-service
spec:
  selector:
    app: app1
    tier: web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: app1
  annotations:
    kubernetes.io/change-cause: initial deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      name: nginx
      labels:
        app: app1
        tier: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.22.0
        ports:
        - containerPort: 80


