# Copyright 2019 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: alphacluster
  namespace: poc
spec:
  topology:
    controlPlane:
      replicas: 1 #optional change to 3 for HA control plane
      storageClass: [choose from `kubectl get vmclass` command]
      tkr:
        reference:
          name: [choose from `kubectl get tkr` command]
      vmClass: [choose from `kubectl get vmclass` command]
    nodePools:
    - name: workers
      replicas: 3 #choose at least 1 node
      storageClass: [choose from `kubectl get vmclass` command]
      vmClass: [choose from `kubectl get vmclass` command]